/**
 * "Spot the fallacy": short original scenarios, each naming one fallacy or bias already written up
 * in content/concepts/{reasoning,fallacies}.json. Titles and colors are read from the graph at
 * render time (see DebatePage.tsx), so only ids live here.
 */
export type QuizItem = {
  id: string;
  prompt: string;
  correct: string;
  distractors: [string, string, string];
  explain: string;
};

export const quiz: QuizItem[] = [
  { id: "q-straw-man",
    prompt: "Senator: “I think we should trim next year's defense budget by two percent.” Opponent: “My colleague wants to leave our country defenseless and at the mercy of every hostile power on Earth.”",
    correct: "straw-man", distractors: ["false-dilemma", "slippery-slope", "appeal-to-emotion"],
    explain: "The opponent swapped “trim two percent” for an extreme, undefended version — “leave us defenseless” — and attacked that instead of the real proposal." },
  { id: "q-ad-hominem",
    prompt: "“You can't trust her opinion on the new tax policy — she dropped out of college.”",
    correct: "ad-hominem", distractors: ["genetic-fallacy", "appeal-to-authority", "tu-quoque"],
    explain: "It dismisses the argument by attacking a trait of the person making it, without engaging with the policy itself." },
  { id: "q-genetic-fallacy",
    prompt: "“That treatment can't possibly work — it started out as a home remedy invented by unlicensed folk healers centuries ago.”",
    correct: "genetic-fallacy", distractors: ["appeal-to-tradition", "ad-hominem", "hasty-generalization"],
    explain: "It judges the claim by where the idea came from, not by the evidence for or against it today." },
  { id: "q-red-herring",
    prompt: "Reporter: “Why did the company's profits fall this quarter?” CEO: “Let me tell you about the wonderful charity partnership we just announced.”",
    correct: "red-herring", distractors: ["appeal-to-emotion", "straw-man", "whataboutism"],
    explain: "The CEO changes the subject entirely instead of answering the question that was actually asked." },
  { id: "q-tu-quoque",
    prompt: "Doctor: “You should really quit smoking — it's terrible for your lungs.” Patient: “You reek of cigarettes yourself, so don't lecture me.”",
    correct: "tu-quoque", distractors: ["ad-hominem", "whataboutism", "red-herring"],
    explain: "It deflects the advice by pointing out the doctor's own hypocrisy, which says nothing about whether the advice is correct." },
  { id: "q-whataboutism",
    prompt: "Journalist: “Your government has been criticized for restricting press freedom.” Official: “What about the country you're from? They imprison journalists too.”",
    correct: "whataboutism", distractors: ["tu-quoque", "red-herring", "false-equivalence"],
    explain: "Rather than answering the specific charge, it points to wrongdoing elsewhere to deflect scrutiny from it." },
  { id: "q-appeal-to-authority",
    prompt: "“This supplement has to work — a famous actor said he takes it every single day.”",
    correct: "appeal-to-authority", distractors: ["bandwagon", "appeal-to-tradition", "appeal-to-novelty"],
    explain: "Fame is not relevant expertise. The claim leans on who said it, not on any evidence that it works." },
  { id: "q-appeal-to-emotion",
    prompt: "“Please don't give me a ticket — my dog is sick and I've had the worst day of my life.”",
    correct: "appeal-to-emotion", distractors: ["appeal-to-consequences", "red-herring", "straw-man"],
    explain: "It appeals to pity rather than to whether the parking violation actually happened." },
  { id: "q-appeal-to-nature",
    prompt: "“Herbal remedies are safer than manufactured drugs, because they're natural.”",
    correct: "appeal-to-nature", distractors: ["appeal-to-tradition", "hasty-generalization", "false-equivalence"],
    explain: "Natural doesn't automatically mean safe — many natural substances, from hemlock to snake venom, are highly toxic." },
  { id: "q-appeal-to-tradition",
    prompt: "“We've always closed the shop on Sundays, so there's no reason to change it now.”",
    correct: "appeal-to-tradition", distractors: ["appeal-to-nature", "bandwagon", "slippery-slope"],
    explain: "How long something has been done is treated as a reason on its own, without asking whether it still makes sense." },
  { id: "q-bandwagon",
    prompt: "“Everyone at school already has the new phone, so obviously I need one too.”",
    correct: "bandwagon", distractors: ["appeal-to-novelty", "appeal-to-tradition", "appeal-to-authority"],
    explain: "Popularity is treated as proof of merit, when a lot of people doing something is not evidence that it's wise." },
  { id: "q-appeal-to-ignorance",
    prompt: "“No one has ever proven that ghosts don't exist, so they must be real.”",
    correct: "appeal-to-ignorance", distractors: ["begging-the-question", "hasty-generalization", "slippery-slope"],
    explain: "A lack of disproof is treated as proof. Absence of evidence against a claim is not evidence for it." },
  { id: "q-false-dilemma",
    prompt: "“Either we ban all cars from downtown, or we accept that pedestrians will keep getting hurt.”",
    correct: "false-dilemma", distractors: ["slippery-slope", "appeal-to-consequences", "straw-man"],
    explain: "It presents only two options when others clearly exist — better crosswalks, lower speed limits, and so on." },
  { id: "q-no-true-scotsman",
    prompt: "“No real vegetarian would ever eat fish.” “But my friend calls herself vegetarian and eats fish sometimes.” “Well then, she's not a real vegetarian.”",
    correct: "no-true-scotsman", distractors: ["begging-the-question", "equivocation", "moving-goalposts"],
    explain: "Rather than revise the original claim in light of a counterexample, the category is quietly redefined to exclude it." },
  { id: "q-moving-goalposts",
    prompt: "“Show me one peer-reviewed study and I'll believe you.” (A study is shown.) “Well, one study isn't enough — show me five independent ones.”",
    correct: "moving-goalposts", distractors: ["appeal-to-ignorance", "no-true-scotsman", "hasty-generalization"],
    explain: "The standard of evidence is raised the moment it's met, so no amount of evidence will ever be enough." },
  { id: "q-equivocation",
    prompt: "“A feather is light. What is light cannot be dark. Therefore, a feather cannot be dark.”",
    correct: "equivocation", distractors: ["false-equivalence", "begging-the-question", "affirming-consequent"],
    explain: "The word “light” quietly shifts meaning midway through, from “not heavy” to “not dark.”" },
  { id: "q-slippery-slope",
    prompt: "“If we let students redo one failed test, soon they'll expect to redo every assignment, and eventually no one will study at all.”",
    correct: "slippery-slope", distractors: ["false-dilemma", "appeal-to-consequences", "hasty-generalization"],
    explain: "It assumes one small step must set off a chain to an extreme outcome, without showing that each link is likely." },
  { id: "q-post-hoc",
    prompt: "“I wore my lucky socks and we won the game, so the socks must have brought us luck.”",
    correct: "post-hoc", distractors: ["correlation-causation", "gamblers-fallacy", "hasty-generalization"],
    explain: "Because one thing followed another, it's assumed to have caused it — the order alone proves nothing." },
  { id: "q-correlation-causation",
    prompt: "“Towns with more churches also report more crime, so churches must be causing the crime.”",
    correct: "correlation-causation", distractors: ["post-hoc", "causal-oversimplification", "base-rate-fallacy"],
    explain: "A third factor — population size — drives both numbers up. Moving together doesn't mean one causes the other." },
  { id: "q-hasty-generalization",
    prompt: "“My rideshare driver today was rude, and so was the one last week. Rideshare drivers must all be rude.”",
    correct: "hasty-generalization", distractors: ["anecdotal-evidence", "cherry-picking", "survivorship-bias"],
    explain: "A sweeping conclusion about a whole group is drawn from a tiny, unrepresentative handful of cases." },
  { id: "q-anecdotal-evidence",
    prompt: "“Statistics say the new medication rarely causes side effects, but my neighbor took it and felt dizzy for a week, so I don't believe those numbers.”",
    correct: "anecdotal-evidence", distractors: ["hasty-generalization", "cherry-picking", "texas-sharpshooter"],
    explain: "One personal story is treated as outweighing a much larger, more carefully gathered body of evidence." },
  { id: "q-cherry-picking",
    prompt: "The report proudly highlighted the one month sales were up, without mentioning the five months before it that were down.",
    correct: "cherry-picking", distractors: ["survivorship-bias", "texas-sharpshooter", "hasty-generalization"],
    explain: "Only the evidence that supports the desired conclusion is shown; everything inconvenient is left out." },
  { id: "q-survivorship-bias",
    prompt: "“Every successful founder I've read about dropped out of college, so dropping out must be a smart strategy.”",
    correct: "survivorship-bias", distractors: ["hasty-generalization", "cherry-picking", "base-rate-fallacy"],
    explain: "It looks only at the winners, ignoring the far larger number of dropouts whose ventures quietly failed." },
  { id: "q-texas-sharpshooter",
    prompt: "Out of a thousand comparisons run on the data, one gene turned up slightly more often in patients with the disease, and researchers announced they'd found the cause.",
    correct: "texas-sharpshooter", distractors: ["cherry-picking", "base-rate-fallacy", "correlation-causation"],
    explain: "With a thousand comparisons, some pattern was bound to turn up by chance alone — the target was painted after the shots were fired." },
  { id: "q-gamblers-fallacy",
    prompt: "“The wheel has landed on black five times in a row, so red is due next.”",
    correct: "gamblers-fallacy", distractors: ["base-rate-fallacy", "hasty-generalization", "texas-sharpshooter"],
    explain: "Independent random events have no memory: the wheel is no more likely to land on red because of what happened before." },
  { id: "q-base-rate-fallacy",
    prompt: "“The test is 99 percent accurate, so if it comes back positive for this very rare disease, I'm almost certainly sick.”",
    correct: "base-rate-fallacy", distractors: ["appeal-to-ignorance", "texas-sharpshooter", "gamblers-fallacy"],
    explain: "It ignores how rare the disease is to begin with — when a condition is rare enough, most positive results are still false alarms." },
  { id: "q-begging-the-question",
    prompt: "“This book is true because it is the word of a perfectly honest author, and we know the author is perfectly honest because the book says so.”",
    correct: "begging-the-question", distractors: ["no-true-scotsman", "equivocation", "appeal-to-authority"],
    explain: "The conclusion is smuggled into the premise, so the argument can only convince someone who already believes it." },
  { id: "q-affirming-consequent",
    prompt: "“If it rained, the streets would be wet. The streets are wet. Therefore, it must have rained.”",
    correct: "affirming-consequent", distractors: ["denying-antecedent", "post-hoc", "causal-oversimplification"],
    explain: "The streets could be wet for other reasons — a sprinkler, a burst pipe. Matching the consequent doesn't prove the antecedent." },
  { id: "q-sunk-cost",
    prompt: "“We've already spent two years and a million dollars on this failing project — we can't stop now.”",
    correct: "sunk-cost", distractors: ["appeal-to-consequences", "moving-goalposts", "motivated-reasoning"],
    explain: "The time and money already spent are gone either way; only what happens from here on should decide whether to continue." },
  { id: "q-confirmation-bias",
    prompt: "She only reads news sites that already agree with her, and waves away anything from other outlets as untrustworthy.",
    correct: "confirmation-bias", distractors: ["motivated-reasoning", "availability-heuristic", "cherry-picking"],
    explain: "Information that fits existing beliefs is sought out and welcomed; information that challenges them is filtered away." },
  { id: "q-dunning-kruger",
    prompt: "After one introductory coding class, he was confident he understood software better than the team's senior engineers.",
    correct: "dunning-kruger", distractors: ["motivated-reasoning", "hindsight-bias", "framing-effect"],
    explain: "With so little real skill, he lacks the very expertise needed to see how much he still doesn't know." },
];
